# Generated by Django 2.0.8 on 2018-08-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_history',
            name='Stop_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qualifications_on_entry',
            name='Year_Attained',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
