# Generated by Django 2.1 on 2018-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_employees',
            name='Summary_of_Performance',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Summary_of_Performance1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Summary_of_Performance2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Summary_of_Performance3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='past_employees',
            name='Summary_of_Performance4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
