# Generated by Django 2.0.8 on 2018-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_history',
            name='Stop_date',
            field=models.DateField(null=True),
        ),
    ]
