# Generated by Django 2.0.8 on 2018-08-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_internship_history_stop_date'),
        ('database', '0002_auto_20180815_0912'),
    ]

    operations = [
    ]
