# Generated by Django 2.0.8 on 2018-09-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_merge_20180816_0333'),
        ('database', '0003_auto_20180823_1002'),
    ]

    operations = [
    ]
